version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      ignore-comments: true
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    godot:
      capital: true
    gosec:
      config:
        G101:
          pattern: (?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|credential
        global:
          "#nosec": gosec-ignore
    govet:
      disable:
        - fieldalignment
      enable-all: true
    inamedparam:
      skip-single-param: true
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
    nlreturn:
      block-size: 3
    nolintlint:
      require-specific: true
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    tagliatelle:
      case:
        rules:
          json: snake
    testpackage:
      skip-regexp: _internal_test\.go
    varnamelen:
      max-distance: 6
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        text: result \d+ \([^)]+\) is always
    paths:
      - \.pb\.go$
      - \.connect\.go$
      - \.sql\.go$
      - _templ\.go$
      - migrate\.go
      - ^.git
      - ^api
      - ^proto
      - ^test
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - \.connect\.go$
      - \.sql\.go$
      - _templ\.go$
      - migrate\.go
      - ^.git
      - ^api
      - ^proto
      - ^test
      - third_party$
      - builtin$
      - examples$
